# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88f298060b65d012d8f0223a2eb5b1e667ac8131b48559827a2b41345e5e2e934c946e757ff1a69c94848ea62d412abb3e7a48cd13061bd315c7725af6f1fd8a

test:
  secret_key_base: e0aee4ccfd8c514c30ce362bb4b361bf7a2100ed42554888682bae2a75de3ef010cea2e56e241d45b77b69c57275e64bae8a1e84e7d57e74c6db4e9a983c598c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
